spring.application.name=api-tabibi-admin-panel

spring.datasource.url=jdbc:sqlserver://eu-az-sql-serv1.database.windows.net:1433;databaseName=ds8yd7gykkw9vej;encrypt=true;trustServerCertificate=true;
spring.datasource.username=u0dxduesbezslbu
spring.datasource.password=	s%a8aMqn!1mqUSGX$0D&pjiA2
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


spring.data.rest.base-path=/magic-api
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.api-docs.data-rest.enabled=false
spring.data.rest.detection-strategy=annotated
